#!/bin/bash

# bspwm
bspc monitor -d 1 2 3 4 5 6
bspc config border_width         0
bspc config window_gap          8
bspc config split_ratio          0.50
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a Chromium desktop='^2'
bspc rule -a Steam desktop='^6'
bspc rule -a "VirtualBox Manager" desktop='^6'

# autostart
xrdb -merge ~/.Xresources &
xsetroot -cursor_name left_ptr &
sxhkd &
xss-lock -- slock &
xset b off &
xset s 300 &
~/.fehbg &
urxvtd &
~/.local/bin/bat_check.sh &
picom &
dunst &
~/.config/polybar/launch.sh
