#! /bin/sh

sxhkd &
dunst &
unclutter &
compton &> /dev/null &
~/.local/bin/bat_check.sh &
redshift -l 13.082680:80.270718 &
~/.fehbg &
urxvtd &

bspc monitor -d term web music files code virt chat game IX X

bspc config border_width         0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Spacefm desktop='^4'

$HOME/.config/polybar/launch.sh &
